package com.github.jparkie.bsd

object WhileKeywords {
  val `;`     = ";"
  val `:=`    = ":="
  val `+`     = "+"
  val `-`     = "-"
  val `/`     = "/"
  val `*`     = "*"
  val `%`     = "%"
  val `==`    = "=="
  val `!=`    = "!="
  val `<`     = "<"
  val `>`     = ">"
  val `<=`    = "<="
  val `>=`    = ">="
  val `AND`   = "AND"
  val `BEGIN` = "BEGIN"
  val `CALL`  = "CALL"
  val `DO`    = "DO"
  val `ELSE`  = "ELSE"
  val `END`   = "END"
  val `FALSE` = "FALSE"
  val `IF`    = "IF"
  val `IS`    = "IS"
  val `NOT`   = "NOT"
  val `OR`    = "OR"
  val `PROC`  = "PROC"
  val `READ`  = "READ"
  val `RES`   = "RES"
  val `SKIP`  = "SKIP"
  val `THEN`  = "THEN"
  val `TRUE`  = "TRUE"
  val `VAL`   = "VAL"
  val `WHILE` = "WHILE"
  val `WRITE` = "WRITE"
}
